//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public long ID { get; set; }
        public string warehouse_name { get; set; }
    }
}
